### PR TITLE
WIP: ToolbarAndroid binding

### PR DESCRIPTION
**Pull request by czystyl**

### CODE REVIEW

**Comment by czystyl** [comment]
@knowbody know the problem with this binding, and please let me know if you find the solution for our undefined error message.

**Comment by knowbody** [comment]
Yeah once I figure it out I let you know

**Comment by czystyl** [comment]
Ok I found the problem so should be ready in this week 💪

**Comment by czystyl** [comment]
@knowbody I found the problem so I'll continue with that PR 😎

**Comment by grabbou** [comment]
Please submit this PR against `bs-react-native` once again. Thank you for your work on that one, but we have merged back all the improvements in the meantime. That means we no longer accept contributions to `rebolt` in its current form.

**Pull request closed without merging**
