### PR TITLE
Wip virtualized list bindings

### PR DESCRIPTION
**Pull request by reinvanimschoot**
Not finished, WIP

### CODE REVIEW

**Comment by knowbody** [comment]
@reinvanimschoot hey any update on this? what's left?

**Comment by reinvanimschoot** [comment]
@knowbody sorry, been having some busy time at work. It is almost finished actually, it just needs some testing to be done. But the implementation is as good as complete right now. Ill see if I can make some time tomorrow.

**Comment by knowbody** [comment]
no worries just wanted to check. I'll wait for you to finish it. Thanks for working on it!

**Comment by knowbody** [comment]
@reinvanimschoot let us know if you will have time to work on it this week. If not, don't worry, we could just continue working based on your PR. But we want to include it in the v1 release which is planned in the next 2 weeks.

**Comment by reinvanimschoot** [comment]
@knowbody I was gonna work on it last week but we had some troubles at work. I could work on it this week but it would be Friday. But it's only the testing that needs to be done. The implementation should be okey!

**Comment by knowbody** [comment]
@reinvanimschoot oh that's great! and we are also missing the docs and the examples.
Ok, so I'm waiting for your update on Friday then, if it happens that you're busy or something, please let us know and we take care of it at the beginning of next week. Sounds good?

**Comment by grabbou** [comment]
Please submit this PR against `bs-react-native` once again. Thank you for your work on that one, but we have merged back all the improvements in the meantime. That means we no longer accept contributions to `rebolt` in its current form.

**Pull request closed without merging**
