### PR TITLE
PermissionAndroid API

### PR DESCRIPTION
**Pull request by czystyl**

### CODE REVIEW

**Comment by knowbody** [comment]
@czystyl what's blocking us to merge this? what else needs to be done?

**Comment by czystyl** [comment]
@knowbody So, today I updated bindings and test on example app, results? It's working very nice! After today's changes, I need to update docs but you can already start reviewing PR.

**Comment by czystyl** [comment]
@knowbody So, today I updated bindings and test on example app, results? It's working very nice! 💪 After today's changes, I need to update docs and wirte one more binding to request many permissions.

**Comment by knowbody** [comment]
awesome! Thank you!

**Pull request merged**
